# Generated by Django 3.0.8 on 2020-08-28 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_email', models.TextField()),
                ('profile_photo', models.ImageField(default='profile/profile.png', upload_to='profile')),
                ('bio', models.TextField(blank=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('followers_list', models.TextField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_list', models.TextField(blank=True)),
                ('following_count', models.IntegerField(default=0)),
                ('posts_liked', models.TextField(blank=True)),
                ('posts_saved', models.TextField(blank=True)),
                ('posts_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_email', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('pid', models.TextField()),
                ('upid', models.TextField()),
                ('content', models.TextField()),
                ('comments_count', models.IntegerField(default=0)),
                ('likes_list', models.TextField(blank=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('relation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relation_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_core.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_email', models.TextField()),
                ('relation_upid', models.TextField()),
                ('date_commented', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('likes_list', models.TextField(blank=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('relation_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_core.Post')),
                ('relation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relation_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_core.UserProfile')),
            ],
        ),
    ]
