# Generated by Django 3.0.8 on 2020-09-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_core', '0002_auto_20200828_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_url',
            field=models.TextField(default='media/profile/profile.png'),
        ),
    ]
