# Generated by Django 3.0.8 on 2020-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_core', '0004_remove_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ucid',
            field=models.TextField(default='sscoder365@gmail.com_202009022_sscoder365@gmail.com_202009040'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo_url',
            field=models.TextField(default='/media/profile/profile.png'),
        ),
    ]
