# Generated by Django 3.0.8 on 2020-09-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_core', '0005_auto_20200904_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_list',
            field=models.TextField(default='admin,'),
        ),
    ]
