# Generated by Django 3.0.8 on 2020-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_core', '0006_auto_20200914_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following_list',
            field=models.TextField(default='sscoder365@gmail.com,'),
        ),
    ]
